apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-go-server-deployment
  labels:
    app: app-go-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-go-server
  template:
    metadata:
      labels:
        app: app-go-server
    spec:
      containers:
        - name: app-go-server
          image: madfisher/app_go-server:latest
          ports:
            - containerPort: 8000
          command: /app
          imagePullPolicy: IfNotPresent
