version: '3.7'

x-logging: &logging
  driver: "json-file"
  options:
    max-size: "200m"
    max-file: "10"
    tag: "{{.ImageName}}|{{.Name}}"

services:
  app_python:
    image: madfisher/server:latest
    command: python -m poetry run uvicorn server.app:app --host 0.0.0.0
    env_file:
      - ../app_python/.env
    volumes:
      - ../app_python:/app
    ports:
      - "8000:8000"
    logging: *logging

  app_go:
    image: madfisher/app_go-server:latest
    command: /app
    volumes:
      - ../app_go:/app
    ports:
      - "8010:8000"
    logging: *logging

  grafana:
    image: grafana/grafana
    container_name: monitoring.grafana
    volumes:
      - grafana-data:/var/lib/grafana
      - ${PWD}/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
    restart: unless-stopped
    expose:
      - 3000
    ports:
      - "3000:3000"
    logging: *logging

  promtail:
    image: grafana/promtail
    container_name: monitoring.promtail
    expose:
      - 9080
    ports:
      - "9080:9080"
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - promtail-data:/var/lib/promtail/positions
      - ${PWD}/promtail/promtail.yml:/etc/promtail/promtail.yml
    command: -config.file=/etc/promtail/promtail.yml
    restart: unless-stopped
    logging: *logging

  loki:
    image: grafana/loki
    container_name: monitoring.loki
    expose:
      - 3100
    ports:
      - "3100:3100"
    volumes:
      - ${PWD}/loki/loki-config.yml:/etc/loki-config.yml
      - loki-data:/tmp/loki/
    command: -config.file=/etc/loki-config.yml
    restart: unless-stopped
    logging: *logging

volumes:
  grafana-data: {}
  loki-data: {}
  promtail-data: {}