apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-python-server-deployment
  labels:
    app: app-python-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-python-server
  template:
    metadata:
      labels:
        app: app-python-server
    spec:
      containers:
        - name: app-python-server
          image: madfisher/server:latest
          ports:
            - containerPort: 8000
          command: ['python', '-m', 'poetry', 'run', 'uvicorn', 'server.app:app', '--host', '0.0.0.0']
          imagePullPolicy: IfNotPresent