name: Go CI

on:
  push:
    paths:
      - 'app_go/**'
      - '.github/workflows/go-ci.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Dependencies
        working-directory: ./app_go
        run: go mod download

      - name: Linter
        run: go vet app_go/app.go

      - name: Tests
        working-directory: ./app_go
        run: go test -v .

  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}my-go-app 
          docker tag my-go-app ${{ secrets.DOCKER_USERNAME }}/my-go-app
          docker push ${{ secrets.DOCKER_USERNAME }}/my-go-app     

  snyk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Snyk to check for vulnerabilities
        uses: npx snyk test --all-projects
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}