name: Go CI

on:
  push:
    paths:
      - 'app_go/**'
      - '.github/workflows/go-ci.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Linter
        run: go vet ./...

      - name: Tests
        run: go test -v ./...

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t my-go-app .
          docker tag my-go-app ${{ secrets.DOCKER_USERNAME }}/my-go-app
          docker push ${{ secrets.DOCKER_USERNAME }}/my-go-app
